CREATE DATABASE college;

USE college;

CREATE TABLE student (
	id INT PRIMARY KEY,
    name VARCHAR (50),
    age INT NOT NULL
);

INSERT INTO student VALUES(1, "SOHAM", 19);
INSERT INTO student VALUES(2, "LILY", 18);

SELECT * FROM student;

SHOW DATABASES